// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240927064722_v5")]
    partial class v5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.BatteryReceiving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batteryserial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebossedNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrsiNo")
                        .HasColumnType("int");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoNo")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Receivedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unitofmeasurement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BatteryReceiving");
                });

            modelBuilder.Entity("api.Models.BatteryReleasing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatteryId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imjno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receivedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserplateNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId")
                        .IsUnique()
                        .HasFilter("[BatteryId] IS NOT NULL");

                    b.ToTable("BatteryReleasing");
                });

            modelBuilder.Entity("api.Models.BatteryReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatteryId")
                        .HasColumnType("int");

                    b.Property<string>("Endorsedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId")
                        .IsUnique()
                        .HasFilter("[BatteryId] IS NOT NULL");

                    b.ToTable("BatteryReturn");
                });

            modelBuilder.Entity("api.Models.BatteryTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessUnitFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessUnitTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNoFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNoTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleasingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransferDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReleasingId");

                    b.ToTable("BatteryTransfer");
                });

            modelBuilder.Entity("api.Models.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessunitDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessunitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessUnit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "Executive Office Ana's Breeders Farm Central Office",
                            BusinessunitName = "Executive"
                        },
                        new
                        {
                            Id = 2,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "FEM"
                        },
                        new
                        {
                            Id = 3,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "PO - Cenlo"
                        },
                        new
                        {
                            Id = 4,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "PO - Broiler"
                        },
                        new
                        {
                            Id = 5,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "PO - Breeder"
                        },
                        new
                        {
                            Id = 6,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "PO - Hatchery"
                        },
                        new
                        {
                            Id = 7,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "CAO"
                        },
                        new
                        {
                            Id = 8,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Cisdevo"
                        },
                        new
                        {
                            Id = 9,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Subzero"
                        },
                        new
                        {
                            Id = 10,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Sales - ABFI"
                        },
                        new
                        {
                            Id = 11,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "PED - Planning"
                        },
                        new
                        {
                            Id = 12,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "PED - Project"
                        },
                        new
                        {
                            Id = 13,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "SFC"
                        },
                        new
                        {
                            Id = 14,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Sales - QP/SCC"
                        },
                        new
                        {
                            Id = 15,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "JPPI"
                        },
                        new
                        {
                            Id = 16,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Research and Development"
                        },
                        new
                        {
                            Id = 17,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "GSII - Blown Film"
                        },
                        new
                        {
                            Id = 18,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "GSII - Recycling"
                        },
                        new
                        {
                            Id = 19,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "GSII - CHB/Ula"
                        },
                        new
                        {
                            Id = 20,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "HR FAIP"
                        },
                        new
                        {
                            Id = 21,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "FAIP Admin"
                        },
                        new
                        {
                            Id = 22,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Dressing Plant"
                        },
                        new
                        {
                            Id = 23,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "QA Department"
                        },
                        new
                        {
                            Id = 24,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Procurement"
                        },
                        new
                        {
                            Id = 25,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Logistics and Warehouse"
                        },
                        new
                        {
                            Id = 26,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "Motor Pool"
                        },
                        new
                        {
                            Id = 27,
                            BusinessLocation = "To be added",
                            BusinessunitDescription = "To be added",
                            BusinessunitName = "SCC"
                        });
                });

            modelBuilder.Entity("api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Admin role for FAIP",
                            Name = "FAIPadmin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Warehouse role for FAIP",
                            Name = "FAIPwarehouse"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Business Unit role",
                            Name = "BusinessUnit"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Super Admin Role",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("api.Models.TireDisposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DisposalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndorsedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TireReturnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TireReturnId")
                        .IsUnique()
                        .HasFilter("[TireReturnId] IS NOT NULL");

                    b.ToTable("TireDisposal");
                });

            modelBuilder.Entity("api.Models.TireRecap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndorsedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecappedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TireReturnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TireReturnId")
                        .IsUnique()
                        .HasFilter("[TireReturnId] IS NOT NULL");

                    b.ToTable("TireRecap");
                });

            modelBuilder.Entity("api.Models.TireReceiving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebossedNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrciNo")
                        .HasColumnType("int");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoNo")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Receivedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TireSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TireType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tirebrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiresize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unitofmeasurement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TireReceiving");
                });

            modelBuilder.Entity("api.Models.TireReleasing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abfiserialno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Driver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imjno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receivedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TireId")
                        .IsUnique()
                        .HasFilter("[TireId] IS NOT NULL");

                    b.ToTable("TireReleasing");
                });

            modelBuilder.Entity("api.Models.TireReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndorsedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TireId")
                        .IsUnique()
                        .HasFilter("[TireId] IS NOT NULL");

                    b.ToTable("TireReturn");
                });

            modelBuilder.Entity("api.Models.TireTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessUnitFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessUnitTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNoFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNoTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleasingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransferDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReleasingId");

                    b.ToTable("TireTransfer");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessUnit = "Cisdevo",
                            DateCreated = new DateTime(2024, 9, 27, 14, 47, 21, 644, DateTimeKind.Local).AddTicks(1444),
                            FirstName = "Admin",
                            LastName = "User",
                            MiddleName = "Admin",
                            PasswordHash = "$2a$11$vhruT9iYxD.GeKmeTriRmOjP80T5V5QQ6Y6nbMni5JoUJYk6Ip25C",
                            Role = "Admin",
                            Username = "000-001"
                        },
                        new
                        {
                            Id = 2,
                            BusinessUnit = "Logistics and Warehouse",
                            DateCreated = new DateTime(2024, 9, 27, 14, 47, 21, 822, DateTimeKind.Local).AddTicks(353),
                            FirstName = "Warehouse",
                            LastName = "User",
                            MiddleName = "Test",
                            PasswordHash = "$2a$11$oeIQmb8kb3RP9zxASxmfwO2Ecw8q3DEPBUqD.cO1R68dQZfjvuEjy",
                            Role = "FAIPwarehouse",
                            Username = "000-002"
                        },
                        new
                        {
                            Id = 3,
                            BusinessUnit = "FAIP Admin",
                            DateCreated = new DateTime(2024, 9, 27, 14, 47, 22, 5, DateTimeKind.Local).AddTicks(8641),
                            FirstName = "FAIP",
                            LastName = "User",
                            MiddleName = "Admin",
                            PasswordHash = "$2a$11$42dvQNWT.Yj/DT9UZQ7jsuhpLZJxhScjAcRIiN67igQ4z7OeHjS0C",
                            Role = "FAIPadmin",
                            Username = "000-003"
                        },
                        new
                        {
                            Id = 4,
                            BusinessUnit = "Subzero",
                            DateCreated = new DateTime(2024, 9, 27, 14, 47, 22, 183, DateTimeKind.Local).AddTicks(7253),
                            FirstName = "Business",
                            LastName = "User",
                            MiddleName = "Unit",
                            PasswordHash = "$2a$11$D/QseoAVYEMJpqrY763tguocjTtec9pSwIIgC.dkbofDZOumJPmf.",
                            Role = "BusinessUnit",
                            Username = "000-004"
                        });
                });

            modelBuilder.Entity("api.Models.BatteryReleasing", b =>
                {
                    b.HasOne("api.Models.BatteryReceiving", "BReceiving")
                        .WithOne("BatteryReleasing")
                        .HasForeignKey("api.Models.BatteryReleasing", "BatteryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BReceiving");
                });

            modelBuilder.Entity("api.Models.BatteryReturn", b =>
                {
                    b.HasOne("api.Models.BatteryReceiving", "BReceiving")
                        .WithOne("BatteryReturn")
                        .HasForeignKey("api.Models.BatteryReturn", "BatteryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BReceiving");
                });

            modelBuilder.Entity("api.Models.BatteryTransfer", b =>
                {
                    b.HasOne("api.Models.BatteryReleasing", "BatteryReleasing")
                        .WithMany("BatteryTransfer")
                        .HasForeignKey("ReleasingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BatteryReleasing");
                });

            modelBuilder.Entity("api.Models.TireDisposal", b =>
                {
                    b.HasOne("api.Models.TireReturn", "TireReturn")
                        .WithOne("TireDisposal")
                        .HasForeignKey("api.Models.TireDisposal", "TireReturnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TireReturn");
                });

            modelBuilder.Entity("api.Models.TireRecap", b =>
                {
                    b.HasOne("api.Models.TireReturn", "TireReturn")
                        .WithOne("TireRecap")
                        .HasForeignKey("api.Models.TireRecap", "TireReturnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TireReturn");
                });

            modelBuilder.Entity("api.Models.TireReleasing", b =>
                {
                    b.HasOne("api.Models.TireReceiving", "TReceiving")
                        .WithOne("TireReleasing")
                        .HasForeignKey("api.Models.TireReleasing", "TireId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TReceiving");
                });

            modelBuilder.Entity("api.Models.TireReturn", b =>
                {
                    b.HasOne("api.Models.TireReceiving", "TReceiving")
                        .WithOne("TireReturn")
                        .HasForeignKey("api.Models.TireReturn", "TireId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TReceiving");
                });

            modelBuilder.Entity("api.Models.TireTransfer", b =>
                {
                    b.HasOne("api.Models.TireReleasing", "TireReleasing")
                        .WithMany("TireTransfer")
                        .HasForeignKey("ReleasingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TireReleasing");
                });

            modelBuilder.Entity("api.Models.BatteryReceiving", b =>
                {
                    b.Navigation("BatteryReleasing");

                    b.Navigation("BatteryReturn");
                });

            modelBuilder.Entity("api.Models.BatteryReleasing", b =>
                {
                    b.Navigation("BatteryTransfer");
                });

            modelBuilder.Entity("api.Models.TireReceiving", b =>
                {
                    b.Navigation("TireReleasing");

                    b.Navigation("TireReturn");
                });

            modelBuilder.Entity("api.Models.TireReleasing", b =>
                {
                    b.Navigation("TireTransfer");
                });

            modelBuilder.Entity("api.Models.TireReturn", b =>
                {
                    b.Navigation("TireDisposal");

                    b.Navigation("TireRecap");
                });
#pragma warning restore 612, 618
        }
    }
}
